services:
  val0:
    hostname: val0
    init: true
    image: rippled:latest
    container_name: val0
    volumes:
    - ./volumes/node0:/etc/opt/ripple/
    command: ["/opt/ripple/bin/rippled", "--start", "--conf", "/etc/opt/ripple/rippled.cfg"]
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      rippled-net:
        ipv4_address: 172.23.0.3

  val1:
    hostname: val1
    init: true
    image: rippled:latest
    container_name: val1
    volumes:
    - ./volumes/node1:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      rippled-net:
        ipv4_address: 172.23.0.4

  val2:
    hostname: val2
    init: true
    image: rippled:latest
    container_name: val2
    volumes:
    - ./volumes/node2:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      rippled-net:
        ipv4_address: 172.23.0.5

  val3:
    hostname: val3
    init: true
    image: rippled:latest
    container_name: val3
    volumes:
    - ./volumes/node3:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      rippled-net:
        ipv4_address: 172.23.0.6

  val4:
    hostname: val4
    init: true
    image: rippled:latest
    container_name: val4
    volumes:
    - ./volumes/node4:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      rippled-net:
        ipv4_address: 172.23.0.7

  val5:
    hostname: val5
    init: true
    image: rippled:latest
    container_name: val5
    volumes:
    - ./volumes/node5:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      rippled-net:
        ipv4_address: 172.23.0.8

  rippled:
    hostname: rippled
    init: true
    build:
      dockerfile: Dockerfile.rippled
    image: rippled:latest
    container_name: rippled
    ports:
      - 0.0.0.0:5005:5005
      - 0.0.0.0:6005:6005
    volumes:
    - ./volumes/rippled/:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "--insecure", "https://localhost:51234/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      rippled-net:
        ipv4_address: 172.23.0.9

  workload:
    hostname: workload
    init: true
    image: workload:latest
    container_name: workload
    command: workload
    networks:
      rippled-net:
        ipv4_address: 172.23.0.10

networks:
  rippled-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.23.0.0/24
